#̷\  ===================================================================
#̷\  PowerShell Module -- PowerShell.Module.ThinProfile
#̷\  
#̷\  Manifest File Generated on Wed, 13 Aug 2025 15:38:02 GMT
#̷\  Current Git Revision 9f4ece2e3a22be6d61f1a79bc93b974c4da7b7ad
#̷\  ===================================================================


@{


    RootModule        =  'PowerShell.Module.ThinProfile.psm1'

    ModuleVersion     = '1.0.7
'

    GUID              = 'b8d816de-1708-4c79-a8b4-7900493954b2'

    CompanyName       = 'Unknown'

    Author            = 'Guillaume Plante'

    Copyright         = '(c) 2020 Guillaume Plante. All rights reserved.'

    Description       = 'MODULE PowerShell.Module.ThinProfile on 17:21 PM'

    PowerShellVersion = '5.0'

    RequiredAssemblies = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PowerShell.Module.ThinProfile')
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/arsscriptum/PowerShell.Module.ThinProfile/blob/main/COPYING'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/arsscriptum/PowerShell.Module.ThinProfile'
        } # End of PSData hashtable
    } # End of PrivateData hashtable


    #̷\  ===================================================
    #̷\     ＭＯＤＵＬＥ ＥＸＰＯＲＴＥＤ ＦＵＮＣＴＩＯＮＳ
    #̷\  ===================================================

	# !NOTE! --- The following functions declaration was automatically generated by the build script. ---
	FunctionsToExport = @(

		# --- Exported Functions from Config.ps1 ---
		"Get-ThinProfileUserCredentialID",
		"Get-ThinProfileAppCredentialID",
		"Get-ThinProfileDevAccountOverride",
		"Set-ThinProfileDevAccountOverride",
		"Get-ThinProfileModuleUserAgent",
		"Set-ThinProfileDefaultUsername",
		"Get-ThinProfileDefaultUsername",
		"Set-ThinProfileServer",
		"Get-ThinProfileServer",
		"Test-ThinProfileModuleConfig",
		"Get-ThinProfileModuleRegistryPath",
		"Get-ThinProfileModuleInformation",

		# --- Exported Functions from ControlMouse.ps1 ---
		"Enable-LocalMouse",
		"Disable-LocalMouse",
		"Get-LocalMouseStatus",
		"Set-RegistryInstanceId",
		"Get-RegistryInstanceId",
		"Get-PSControlsRegistryRoot",

		# --- Exported Functions from Helpers.ps1 ---
		"Get-DateForFileName",
		"Get-DateString",
		"Get-UnixTime",
		"ConvertTo-UnixTime",
		"ConvertFrom-UnixTime",
		"ConvertTo-CTime",
		"ConvertFrom-Ctime",
		"Write-ProgressHelper",
		"Show-ModuleInstallPaths",
		"Wait-ThinProfileModuleUpdate",
		"Invoke-EnsureSharedScriptFolder",
		"Write-ThinProfileHost",

		# --- Exported Functions from Initialize.ps1 ---
		"Initialize-ThinProfileModule",
		"Uninitialize-ThinProfileModule",
		"AutoInitialize-ThinProfileModule",

		# --- Exported Functions from ManageScreenshots.ps1 ---
		"Invoke-ManageScreenshotArchive",

		# --- Exported Functions from MessageBox.ps1 ---
		"Register-ScriptAssemblies",
		"Show-MessageBoxAsyncPing",
		"Show-MessageBoxServices",
		"Show-MessageBoxScriptError",
		"Show-MessageBoxVideoUrlExtended",
		"Show-MessageBoxVideoSydney",
		"Show-MessageBoxRestart",
		"Show-MessageBoxStandby",
		"Show-MessageBoxInfo",
		"Show-BeAdvisedSydney",
		"Show-MessageBoxError",
		"Show-MessageBoxVideoUrl",
		"Show-MessageBoxException",
		"Test-Popupcolors",
		"Show-MessageBox",
		"Test-SimpleMsgBox2",
		"Test-SimpleMsgBox",
		"Show-SimpleMessageBox",
		"Show-Popup",
		"Get-MessageBoxResult",
		"Show-UserInfo",
		"Show-MessageBoxVoice",

		# --- Exported Functions from ModulesPathFunctions.ps1 ---
		"Push-ModReddit",
		"Push-ModShellGPT",
		"Push-ModShim",
		"Push-ModTakeOwnership",
		"Push-ModTerminal",
		"Push-Modter2K",
		"Push-ModTorrentsManager",
		"Push-ModWindowsHost",
		"Push-ModWorkflowTools",
		"Push-ModProfileUtils",
		"Push-ModTools",
		"Push-ModOpenAI",
		"Push-ModNtRights",
		"Push-ModMiniPc",
		"Push-ModManageMini",
		"Push-ModGithub",
		"Push-ModExpressVPN",
		"Push-ModDownloader",
		"Push-ModDocker",
		"Push-ModCryptography",
		"Push-ModCore",
		"Push-ModCompiler",
		"Push-ModAssert",
		"Push-Mod1190",
		"Push-Mod1138",

		# --- Exported Functions from ModuleUpdater.ps1 ---
		"Invoke-ThinProfileAutoUpdate",
		"Get-ThinProfileAutoUpdateOverride",
		"Set-ThinProfileAutoUpdateOverride",
		"New-ThinProfileModuleVersionFile",
		"Get-ThinProfileModuleVersionPath",

		# --- Exported Functions from ModuleVersion.ps1 ---
		"Get-ThinProfileModuleVersion",

		# --- Exported Functions from NetDelayedTask.ps1 ---
		"New-DelayedScheduledTask",
		"New-EncodedScheduledTask",
		"Read-QueuedCommandLogs",
		"Open-QueuedCommandLogs",
		"Stop-QueuedCommandProcessor",
		"Start-QueuedCommandProcessor",
		"Invoke-ProcessQueuedCommands",

		# --- Exported Functions from OpenPage.ps1 ---
		"Stop-OpenPageTask",
		"Invoke-OpenPageDesjardins",
		"Invoke-OpenPageSecurityAdvisory",
		"Open-CustomPage",
		"Stop-PowerShellProcesses",
		"Stop-PidFromTempFile",
		"Save-CurrentPidToTempFile",
		"New-OpenPageTask",
		"Read-OpenCustomPageLogFile",

		# --- Exported Functions from Robocopy.ps1 ---
		"Write-RoboLog",
		"Add-RobocopyPrivileges",
		"Remove-RobocopyPrivileges",
		"Invoke-Robocopy",
		"Invoke-UserHomeClone",
		"Grant-DirectoryPermission",
		"ConvertFrom-AclDirectorySec",

		# --- Exported Functions from ScheduledTaskDetails.ps1 ---
		"Archive",
		"Remove-SchedTasks",
		"Get-ScheduledTaskDetails",
		"Test-SerializableProperty",
		"Unregister-AllSchedTasks",
		"Convert-SchedTaskStateValueToString",
		"ConvertFrom-CimType",
		"Show-SchedTasksDebugInfo",
		"Clear-SchedTasks",
		"Add-SchedTasks",
		"Read-SchedTaskProperties",
		"Write-SchedTaskProperties",
		"Remove-SchedTaskProperties",
		"Set-EventChannelEnable",
		"Get-ScheduledTaskRunHistory",
		"Get-SchedTasks",

		# --- Exported Functions from ShowSydneyMsgBox.ps1 ---
		"Show-Sydney",
		"Show-MessageBoxVideoSydney",
		"ConvertFrom-Base64CompressedScriptBlock",

		# --- Exported Functions from WinNotification.ps1 ---
		"Read-TaskNotifyLogFile",
		"Invoke-StartNotify",
		"Show-LowMemoryNotificationFR",
		"Invoke-StopNotify",

		# --- Exported Functions from WinUpdateNotify.ps1 ---
		"Show-LocalWinUpdateNotification",
		"Get-XamlUiContent",
		"Invoke-WinUpdateTask",
		"Show-LowMemoryNotificationFR")
	

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＥＸＰＯＲＴＥＤ ＡＬＩＡＳＥＳ
    #̷\  ===================================================

	# !NOTE! --- The following alias declaration was automatically generated by the build script. ---
	# List of all aliases packaged with this module

	AliasesToExport = @(
		"DoScriptsCheck",
		"onlogin",
		"touch",
		"x")

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＦＩＬＥＳ 
    #̷\ （ＩＦ ＣＯＭＰＲＥＳＳＥＤ， ＷＩＬＬ ＢＥ ＥＭＰＴＹ）
    #̷\  ===================================================

	FileList = @()

}




